USE bunnyxproduction;
GO;
INSERT INTO headphones(discount, img, label, description, price) VALUES(20, "../RESSOURCES/Headphones//Headphone1.jpg", "somic g951s pink", "somic cat ear headset for Sale OFF 73", 235.02);
GO;
INSERT INTO headphones(discount, img, label, description, price) VALUE(70, "../RESSOURCES/Headphones//Headphone2.jpg", "Cute Cat Headphone", "Cute Cat Ear Flash Tws Stereo Bluetooth 5.0 Earphone Headset LED Wireless Headphone with microphone for Girls Love Gaming", 152.99);
GO;
-- UPDATE headphones SET img = "C:\Users\ADAM\OneDrive\Documents\DEV101\AARABANE\SITES STATIQUES\PROJECT\BUNNYxPRODUCTION\RESSOURCES\Headphones" WHERE id = 2;
ALTER TABLE headphones;
GO;
ALTER COLUMN description VARCHAR(40);
GO;
INSERT INTO headphones(img, label, description, price) VALUE("../RESSOURCES/Headphones//Headphone3.jpg", "SOMiC GS510 2.4G Wireless", "SOMiC GS510 2.4G Wireless Cat Ear Pink Headphones With 4 Covers Games/Video/Live 3 Modes Headset for PS5/PS4/PC Retractable Mic", 723.05);
GO;
INSERT INTO headphones(discount, img, label, description, price) VALUE(8, "../RESSOURCES/Headphones//Headphone4.jpg", "New Onikuma K9 PINK", "New Onikuma K9 PINK cute cat ear gaming headset, head-mounted 7.1 channel gaming headset with microphone", 480.01);
GO;
INSERT INTO headphones(discount, img, label, description, price) VALUE(79, "../RESSOURCES/Headphones//Headphone5.jpg", "Onikuma K9 3.5 Pink Edition", "Onikuma K9 3.5 Pink Edition head-mounted 7.1 channel gaming headset with microphone", 220.88);
GO;
INSERT INTO headphones(discount, img, label, description, price) VALUE(3, "../RESSOURCES/Headphones//Headphone6.jpg", "MINISO On Ear Headphone with Mic", "MINISO On Ear Headphone with Mic Pink Edition head-mounted 7.1 channel gaming headset with microphone", 133.00);
GO;